---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-full.yml
#
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

## X-Pack security credentials
#
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: changeme

## Uncomment the followings after setting up new password
#
# xpack.monitoring.enabled: true
# xpack.monitoring.elasticsearch.username: logstash_system
# xpack.monitoring.elasticsearch.password: logstash_system-password
